// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzC_cDbvxYGL7RDsMWevwHdKVyqd5xatA',
    appId: '1:75969170393:web:1c733d50b71f957ff7a7c8',
    messagingSenderId: '75969170393',
    projectId: 'organicappauth',
    authDomain: 'organicappauth.firebaseapp.com',
    storageBucket: 'organicappauth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYfwNHkXh-CyXEehkJtjTUz0frIRTsyHI',
    appId: '1:75969170393:android:124fcefcc355a8c9f7a7c8',
    messagingSenderId: '75969170393',
    projectId: 'organicappauth',
    storageBucket: 'organicappauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwpVkGGUaHnGzLo9y9o48-OpNHKbadIhk',
    appId: '1:75969170393:ios:69084d8082eee726f7a7c8',
    messagingSenderId: '75969170393',
    projectId: 'organicappauth',
    storageBucket: 'organicappauth.appspot.com',
    iosBundleId: 'com.example.organicEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwpVkGGUaHnGzLo9y9o48-OpNHKbadIhk',
    appId: '1:75969170393:ios:a38b028a1b0eb64bf7a7c8',
    messagingSenderId: '75969170393',
    projectId: 'organicappauth',
    storageBucket: 'organicappauth.appspot.com',
    iosBundleId: 'com.example.organicEcommerceApp.RunnerTests',
  );
}
